---
title: "Sabrina Gusola - 668568900"
output: html_document
---
## Portfolio Submission Details

**Live Website URL:** https://sabrina-gusola.github.io  
**Project Type:** Individual Portfolio  

---

## Welcome

Welcome to my portfolio website. My name is **Sabrina Gusola**, and I am a Business Administration student with experience in financial office administration, customer service, interior/exterior decorating and both physical and graphic design. This portfolio was created as part of my MGMT 230 show that I am capable of creating and designing a website in R.

---

## Who I Am

I am energetic, adaptable, and approachable, with experience in financial services, retail, and office environments. I enjoy combining organization, analytics, and creativity, and I am especially interested in marketing, design, and client-focused work. I am beginning to use R and RStudio to support basic data analysis tasks that relate to business and communication.

---

## Skills and Focus Areas

- Basic R programming and RStudio  
- Introductory data visualization using **ggplot2** api
- Business and office administration  
- Customer service and client communication  
- Social media content ideas
- Organization, time management, and attention to detail  

